- name: actions/checkout
  value: awesome-checkout-action
- name: 'Checkout V\d'
  value: Super Checkout V6
  regex: true
- name: EXTERNAL_VAR
  value: from-external-file
- name: PROJECT_NAME
  value: "Awesome Project"
