- name: actions/checkout
  value: awesome-checkout-action
- name: 'Checkout V4'
  value: Super Checkout V6
  regex: true
- name: EXTERNAL_VAR
  value: from-external-file
- name: PROJECT_NAME
  value: "Awesome Project"
- name: "<!-- Test update for PR fix verification -->"
  value: "<!-- PR fix verified at 2025-06-24 -->"


