- name: actions/checkout
  value: awesome-checkout-action
- name: 'Checkout V4'
  value: Super Checkout V6
  regex: true
- name: EXTERNAL_VAR
  value: from-external-file
- name: '[A-Z]+_NAME'
  value: Super Awesome Project
