- name: actions/checkout
  value: awesome-checkout-action
- name: Checkout V4
  value: Super Checkout V7
- name: EXTERNAL_VAR
  value: from-external-file
- name: PROJECT_NAME
  value: "Awesome Project"
- name: '([A-Za-z0-9_-]+) references'
  value: 'Super \1 references'
