envs:
  - name: actions/checkout
    value: awesome-checkout-action
  - name: Checkout V4
    value: Super Checkout V5
sources:
  - repo: actions/checkout
    ref: main
    files:
    - README.md
  - repo: actions/labeler
    ref: main
    files:
    - .gitignore