- name: actions/checkout
  value: awesome-checkout-action
- name: Checkout V4
  value: Super Checkout V6
- name: EXTERNAL_VAR
  value: from-external-file
- name: PROJECT_NAME
  value: "Awesome Project"
