name: Repo File Sync
description: 'Synchronize files from repositories'
author: 'Studist Corporation'

branding:
  icon: download
  color: orange

inputs:
  token:
    description: 'The `token` to used for authenticating with GitHub.'
  username:
    description: 'The `username` to use in the git commit.'
  email:
    description: 'The `email` to use in the git commit.'
  reviewers:
    required: false
    description: 'The `reviewers` to use in the pull request to be created.'
  team_reviewers:
    required: false
    description: 'The `team_reviewers` to use in the pull request to be created.'

runs:
  using: node16
  main: dist/index.js
